# -*- coding: utf-8 -*-
#
# This file is part of Flask-SSO
# Copyright (C) 2014, 2015 CERN.
#
# Flask-SSO is free software; you can redistribute it and/or modify
# it under the terms of the Revised BSD License; see LICENSE file for
# more details.

# Travis CI file, that integrates with coveralls for reporting test coverage.

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install --upgrade pip
  - pip install coveralls
  - pip install .

script:
  - coverage run --source=flask_sso setup.py test

after_success:
  - coveralls

notifications:
  email: false

deploy:
  provider: pypi
  user: jirikuncar
  password:
    secure: txNr7JfTM8P69jTi8OJygQdUtKsw6f6BaBzG7OrqQ739x1wLlR6TO4282rHga/Cq4SMyGD9FHebhS1craYV1WmmsgebXpU1sP6RNYMXsBvQjloNTRbf8AnzEsB2GwC5fIHUgvKBVkXNAxm47atfu2QDlWnykvIqOeOi+IZLDk2Q=
  on:
    python: "2.7"
    repo: inveniosoftware/flask-sso
    tags: true
